# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=50, verbose_name='主机名')),
                ('ip', models.CharField(default='', max_length=50, verbose_name='IP地址')),
                ('information', models.CharField(default='', max_length=300, verbose_name='硬件配置')),
                ('OSname', models.CharField(default='', max_length=300, verbose_name='系统镜像')),
                ('role', models.CharField(choices=[('Product', '生产环境'), ('Test', '测试环境')], default='Test', max_length=50, verbose_name='所属环境')),
                ('buildtime', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('service', models.CharField(default='', max_length=600, verbose_name='部署服务')),
                ('manager', models.CharField(default='', max_length=300, verbose_name='负责人')),
                ('beizhu', models.CharField(default='', max_length=300, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产信息',
                'verbose_name_plural': '资产信息',
            },
        ),
    ]
